### ISSUE TITLE
GM Screen doesn't export well

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#13] opened 2024-06-28 00:51 UTC
I've tested this first on v11, then bit the bullet and upgraded to v12 and have the same issue.

The GM Screen exports only as "undefined"

```
---
title: "GM Screen"
icon: ":sticky-note:"
aliases: "GM Screen"
foundryId: JournalEntry.McEmh68SPzvXTsVJ.JournalEntryPage.lQ9MmX3zg4Bd9hjb
tags:
  - JournalEntryPage
---
Below you will find list of shortcuts to subjects that are useful for to GM's, grouped by theme

**Reference Tables Actions & Skills**

  

| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| --- | --- | --- | --- |
| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] |  |  |

**Death & Recovery Terrain & Environment**

  

| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| --- | --- | --- | --- |
| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] |  |  |  |

**Gamemastery Equipment & Services**

  

| [[undefined]] | [[undefined]] | [[undefined]] |
| --- | --- | --- |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] | [[undefined]] |

**Misc** **Variant Rules**

  

| [[undefined]] | [[undefined]] | [[undefined]] |
| --- | --- | --- |
| [[undefined]] | [[undefined]] | [[undefined]] |
| [[undefined]] | [[undefined]] |  |
```

**Comment by MostTornBrain** [comment] 2024-06-28 02:20
This was a curious little puzzle.  I have figured out the root cause and have a rough fix.   I should have a fix posted tomorrow night (6/28).

**Comment by MostTornBrain** [comment] 2024-06-28 02:21
A similar problem occurs with the Player Screen.  This upcoming fix will address that one as well.

**Comment by scooper4711** [comment] 2024-06-28 13:58
I’m happy I could provide you with some entertainment! 😺

**Comment by MostTornBrain** [comment] 2024-06-29 02:18
v0.9.10 addresses most of the issues.   I thought I had it all working properly, but there is some nuance involved.  There are still a few links in the GM Screen that don't get converted.  The issue is the items linked to are not retrievable from Foundry in a synchronous manner (which the export process requires, unfortunately) and as a result, the lookup of the linked document fails.   You'll see this for 3 or 4 links in the GM Screen where they appear as UUID links that don't exist. 

As a work-around for this,  if you import the "PF2E Journal" so you have a local copy, and then export it, _that_ export _will_ work correctly for all the links.

**Comment by scooper4711** [comment] 2024-06-29 20:13
Did the workaround, got a good GM screen exported, but noticed now that some of the pages it links to don't have good tables, e.g. Proficiency Without Level.

The tables lack a blank line between the title and the table, thus preventing the table from rendering.

It's several pages that suffer from this.

**Comment by MostTornBrain** [comment] 2024-06-29 21:56
Yeah, the table thing is unavoidable at the moment - the table creation is part of the HTML to markdown conversion that's done by a built-in 3rd-party routine called TurndownService that was included in the original Markdown Exporter.    It's a quick edit by hand to correct for now.   When I have time I'll see if maybe I can detect the issue with a regex after the markdown code is generated and automatically insert the necessary blank line.

**Comment by MostTornBrain** [comment] 2024-06-29 22:37
Interestingly, I already had added some custom code to handle adding a blank line in front a table because it was an issue in some other exports.  However, in this instance, the problem is happening within the TurndownService conversion as the item shown preceding the table is actually part of the HTML table tag (it is a caption).   So, it looks like I need to add some code to do something special with table captions so they don't break the markdown rendering.

**Comment by MostTornBrain** [comment] 2024-06-29 22:50
v0.9.11 should fix the blank line needed between a table caption and the table.

**Comment by scooper4711** [comment] 2024-06-29 23:34
For your records/completeness, here are all the files that export with "undefined". Note that the same workaround (import, then export) works for Archetypes as with GM Screen.

```
./Journals/PF2e Journals/Archetypes/Scrollmaster.md
./Journals/PF2e Journals/Archetypes/Hellknight Signifer.md
./Journals/PF2e Journals/Archetypes/Hellknight.md
./Journals/PF2e Journals/Archetypes/Spellmaster.md
./Journals/PF2e Journals/Archetypes/Swordmaster.md
./Journals/PF2e Journals/GM Screen/GM Screen.md
./Journals/PF2e Journals/GM Screen/Treasure Per Encounter.md
./Journals/PF2e Journals/GM Screen/Lifestyle Expenses.md
./Journals/PF2e Journals/GM Screen/Light Effects.md
./Journals/PF2e Journals/GM Screen/Detecting Creatures.md
./Journals/PF2e Journals/GM Screen/Treasure.md
./Journals/PF2e Journals/GM Screen/Player Screen.md
./Journals/PF2e Journals/GM Screen/Proficiency Without Level.md
./Journals/PF2e Journals/GM Screen/Learn a Spell.md
```

**Comment by scooper4711** [comment] 2024-06-29 23:35
so to be clear, I've got everything exported well now. A minor workaround for two compendium items and everything renders well.

**Comment by MostTornBrain** [comment] 2024-06-29 23:39
Ok, thanks for the summary.   At some point hopefully I'll figure out a way to get those exporting directly from the Compendium without the workaround.  I'm going to close this issue for now.

**Closed by MostTornBrain** 2024-06-29 23:39 UTC
